### ISSUE TITLE
Error: ./src/plugins/strapi-plugin-upstash-ratelimit couldn't be resolved        

### ISSUE THREAD

**Issue by voidless-03** [upstash/strapi-plugin-upstash-ratelimit#3]
I am using Strapi version 4.25.2. I get the following error:

` Error: ./src/plugins/strapi-plugin-upstash-ratelimit couldn't be resolved                                                                                                 │
│       at toDetailedDeclaration (C:\Users\sshourov\Documents\GitHub\voidless\strapi\node_modules\@strapi\strapi\dist\core\loaders\plugins\get-enabled-plugins.js:41:17)      │
│       at C:\Users\sshourov\Documents\GitHub\voidless\strapi\node_modules\@strapi\strapi\dist\core\loaders\plugins\get-enabled-plugins.js:86:10                              │
│       at C:\Users\sshourov\Documents\GitHub\voidless\strapi\node_modules\lodash\lodash.js:4967:15                                                                           │
│       at baseForOwn (C:\Users\sshourov\Documents\GitHub\voidless\strapi\node_modules\lodash\lodash.js:3032:24)                                                              │
│       at C:\Users\sshourov\Documents\GitHub\voidless\strapi\node_modules\lodash\lodash.js:4936:18                                                                           │
│       at Function.forEach (C:\Users\sshourov\Documents\GitHub\voidless\strapi\node_modules\lodash\lodash.js:9410:14)                                                        │
│       at Module.getEnabledPlugins (C:\Users\sshourov\Documents\GitHub\voidless\strapi\node_modules\@strapi\strapi\dist\core\loaders\plugins\get-enabled-plugins.js:83:22)   │
│       at async Object.loadPlugins (C:\Users\sshourov\Documents\GitHub\voidless\strapi\node_modules\@strapi\strapi\dist\core\loaders\plugins\index.js:75:26)                 │
│       at async Strapi.loadPlugins (C:\Users\sshourov\Documents\GitHub\voidless\strapi\node_modules\@strapi\strapi\dist\Strapi.js:311:5)                                     │
│       at async Promise.all (index 3)    `

**Comment by voidless-03** [comment]
Removing the resolve line from the config fixed my issue

**Comment by voidless-03** [comment]
Also will this plugin be supported for strapi 5?
